---
# tasks file for ubuntu-optimize
#- name: Remove outdated known_hosts entry
#  ansible.builtin.command:
#    #cmd: ssh-keygen -f "/home/ubuntu/.ssh/known_hosts" -R "{{ ansible_default_ipv4.address }}"
#    cmd: ssh-keygen -f "/home/ubuntu/.ssh/known_hosts" -R "{{ ansible_host }}"
#    changed_when: true
#    delegate_to: localhost

- name: Scan and update known_hosts
  ansible.builtin.shell:
    cmd: ssh-keyscan -H {{ ansible_default_ipv4.address }} >> "/home/ubuntu/.ssh/known_hosts"
  changed_when: true
  delegate_to: localhost

- name: Copy sources.list
  copy:
    src: sources.list
    dest: /etc/apt/sources.list

- name: copy file to sudoers.d
  copy:
    src: ubuntu
    dest: /etc/sudoers.d/ubuntu

- name: ensure ssh public key is added to authorized_keys
  ansible.posix.authorized_key:
    user: ubuntu
    key: "{{ lookup('file', 'ubuntu_id_rsa.pub') }}"
    state: present

- name: ensure ssh public key of root is added to authorized_keys
  ansible.posix.authorized_key:
    user: root
    key: "{{ lookup('file', 'root_id_rsa.pub') }}"
    state: present

- name: set up limit.conf
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      root            soft    nofile          100001
      root            hard    nofile          100002
      *               soft    nofile          100001
      *               hard    nofile          100002
      root            soft    memlock         unlimited
      root            hard    memlock         unlimited
      *               soft    memlock         unlimited
      *               hard    memlock         unlimited

- name: ulimit -a
  shell: ulimit -a
  register: limit_out

- debug:
    var: limit_out.stdout_lines

- name: set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

#- shell: echo "ubuntu:Mudata#1028" | chpasswd

- name: Set password for target ubuntu
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    state: present

## Task 2: Set HISTSIZE in .bashrc
#- name: Configure HISTSIZE
#  ansible.builtin.lineinfile:
#    path: "/home/{{ target_user }}/.bashrc"
#    regexp: '^HISTSIZE='
#    line: "HISTSIZE={{ hist_size }}"
#    state: present
#  when: not system_wide | default(false)
#
## Task 3: Set HISTFILESIZE in .bashrc
#- name: Configure HISTFILESIZE
#  ansible.builtin.lineinfile:
#    path: "/home/{{ target_user }}/.bashrc"
#    regexp: '^HISTFILESIZE='
#    line: "HISTFILESIZE={{ hist_file_size }}"
#    state: present
#  when: not system_wide | default(false)
#
## Task 4: Set HISTTIMEFORMAT in .bashrc
#- name: Configure HISTTIMEFORMAT
#  ansible.builtin.lineinfile:
#    path: "/home/{{ target_user }}/.bashrc"
#    regexp: '^HISTTIMEFORMAT='
#    line: "HISTTIMEFORMAT={{ hist_time_format }}"
#    state: present
#  when: not system_wide | default(false)

- name: set up .bashrc of ubuntu
  blockinfile:
    path: /home/ubuntu/.bashrc
    block: |
      HISTSIZE={{ hist_size }}
      HISTFILESIZE={{ hist_file_size }}
      HISTTIMEFORMAT={{ hist_time_format }}

- name: set up .bashrc of root
  blockinfile:
    path: /root/.bashrc
    block: |
      HISTSIZE={{ hist_size }}
      HISTFILESIZE={{ hist_file_size }}
      HISTTIMEFORMAT={{ hist_time_format }}
